services:
    client:
        build:
            context: .
            dockerfile: client.Dockerfile
        depends_on:
            - backend
        ports:
            - "8501:8501"
        networks:
            - my_network
    backend:
        build:
            context: .
            dockerfile: backend.Dockerfile

        ports:
            - "54545:54545"
        networks:
          - my_network

networks:
  my_network:
    driver: bridge
