[tool.poetry]
name = "img-classifier"
version = "0.1.0"
description = ""
package-mode = false
authors = ["Ilya Mevshiy <ilyamevshiy@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/AI-YP-24-6/img_classifier"


[tool.poetry.dependencies]
python = "~3.12"
jupyter = "~1.1.1"
ipykernel = "~6.29.5"
pandas = "~2.2.3"
kaggle = "^1.6.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
