name: pre-commit hooks check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
          python-version: '3.13'

    - name: Run pre-commit on codebase
      uses: pre-commit/action@v3.0.1
      continue-on-error: true

    - name: Auto commit action
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Apply pre-commit hooks auto-fix
